---
- name: Basic setup for Amazon Linux 2
  hosts: all
  become: yes

  tasks:
    - name: Update all packages
      yum:
        name: "*"
        state: latest

    - name: Ensure a list of yum packages are installed
      yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
        - python-pip
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
        - amazon-linux-extras

    - name: Add extras repository
      shell: yum-config-manager --enable extras

    - name: Install basic packages
      yum:
        name:
          - git
          - vim
          - htop
        state: present
